export const KNOWN_BRANDS = [
  "Jack Daniel",
  "Black Label",
  "Red Label",
  "Ballantine Finest",
  "Chivas Regal",
  "Old Par",
  "Royal Circle",
  "Thomas Crown",
  "Havana Club",
  "Havana",
  "Abuelo añejo",
  "Viejo Caldas",
  "Malibu de coco",
  "Flor de Caña",
  "Barcelo",
  "Ojos de tigre",
  "Ramazzotti",
  "Amarula",
  "Jagermeister",
  "Sheridans",
  "Baileys",
  "Four Loko",
  "Beefeater",
  "Antiqueño",
  "Blanco del Valle",
  "Dona camila",
  "Doña Camila",
  "Olmeca",
  "Tequila Chocolate",
  "José Cuervo",
  "Absolut",
];
